/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import service.Connector;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * @author Admin
 */
class Home extends javax.swing.JFrame {
    Connection connection;
    String username;

    /**
     * Creates new form Home
     */
    public Home(String username) {
        Connector connector = new Connector();
        connection = connector.connect();

        this.username = username;
        setTitle(username + "'s Ledger");

        initComponents();
        setColor(btn.get(0));
        ind.get(0).setOpaque(true);
        resetColor(new JPanel[]{btn.get(1), btn.get(2), btn.get(3)}, new JPanel[]{ind.get(1), ind.get(2), ind.get(3)});
        jProgressBar1.setValue(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new JPanel();
        btn = new ArrayList<>();
        for (int i = 0; i < 4; i++) {
            btn.add(new JPanel());
        }
        jLabel = new ArrayList<>();
        for (int i = 0; i < 17; i++) {
            jLabel.add(new JLabel());
        }
        ind = new ArrayList<>();
        for (int i = 0; i < 4; i++) {
            ind.add(new JPanel());
        }
        jPanel = new ArrayList<>();
        for (int i = 0; i < 6; i++) {
            jPanel.add(new JPanel());
        }
        jTextField1 = new JTextField();
        jSeparator1 = new JSeparator();
        jProgressBar1 = new JProgressBar();
        btn_exit = new JLabel();
        button1 = new java.awt.Button();
        insertBtn = new JButton();
        deleteBtn = new JButton();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(LedgerMain.BG_COLOR);
        setLocationByPlatform(true);
//        setUndecorated(true); // remove title bar
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn.get(0).setBackground(new java.awt.Color(23, 35, 51));
        btn.get(0).addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        ind.get(0).setOpaque(false);
        ind.get(0).setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind.get(0));
        ind.get(0).setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
                ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
                ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel.get(7).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(7).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(7).setText("Home");

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn.get(0));
        btn.get(0).setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
                btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_1Layout.createSequentialGroup()
                                .addComponent(ind.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel.get(7))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_1Layout.setVerticalGroup(
                btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_1Layout.createSequentialGroup()
                                .addComponent(ind.get(0), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel.get(7), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn.get(0), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));

        btn.get(1).setBackground(new java.awt.Color(23, 35, 51));
        btn.get(1).addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_2MouseReleased(evt);
            }
        });

        ind.get(1).setOpaque(false);
        ind.get(1).setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind.get(1));
        ind.get(1).setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
                ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
                ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel.get(8).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(8).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(8).setText("Settings");

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn.get(1));
        btn.get(1).setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
                btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_2Layout.createSequentialGroup()
                                .addComponent(ind.get(1), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel.get(8))
                                .addGap(0, 40, Short.MAX_VALUE))
        );
        btn_2Layout.setVerticalGroup(
                btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_2Layout.createSequentialGroup()
                                .addComponent(ind.get(1), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel.get(8), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn.get(1), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, -1));

        btn.get(2).setBackground(new java.awt.Color(23, 35, 51));
        btn.get(2).addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        ind.get(2).setOpaque(false);
        ind.get(2).setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind.get(2));
        ind.get(2).setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
                ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
                ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel.get(9).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(9).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(9).setText("Users");

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn.get(2));
        btn.get(2).setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
                btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_3Layout.createSequentialGroup()
                                .addComponent(ind.get(2), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel.get(9))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
                btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_3Layout.createSequentialGroup()
                                .addComponent(ind.get(2), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel.get(9), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn.get(2), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        btn.get(3).setBackground(new java.awt.Color(23, 35, 51));
        btn.get(3).addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_4MousePressed(evt);
            }
        });

        ind.get(3).setOpaque(false);
        ind.get(3).setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind.get(3));
        ind.get(3).setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
                ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
                ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel.get(10).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(10).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(10).setText("Profile");

        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn.get(3));
        btn.get(3).setLayout(btn_4Layout);
        btn_4Layout.setHorizontalGroup(
                btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_4Layout.createSequentialGroup()
                                .addComponent(ind.get(3), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel.get(10))
                                .addGap(0, 48, Short.MAX_VALUE))
        );
        btn_4Layout.setVerticalGroup(
                btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btn_4Layout.createSequentialGroup()
                                .addComponent(ind.get(3), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(btn_4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel.get(10), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        side_pane.add(btn.get(3), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        jPanel.get(0).setBackground(new java.awt.Color(71, 120, 197));
        jPanel.get(0).addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel.get(0).addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(123, 156, 225));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel.get(6).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel.get(0));
        jPanel.get(0).setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(747, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel.get(6))
                                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(19, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel.get(6), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        getContentPane().add(jPanel.get(0), new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        jPanel.get(1).setBackground(new java.awt.Color(71, 120, 197));

        jPanel.get(2).setBackground(new java.awt.Color(120, 168, 252));
        jPanel.get(2).setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.get(3).setBackground(new java.awt.Color(84, 127, 206));

        jLabel.get(0).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Contacts_25px.png"))); // NOI18N

        jLabel.get(2).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Calendar_25px.png"))); // NOI18N

        jLabel.get(3).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Lock_25px.png"))); // NOI18N
        jLabel.get(3).addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LedgerMap ledgerMap = new LedgerMap(Home.this);
                ledgerMap.setVisible(true);
            }
        });
        jProgressBar1.setBackground(new java.awt.Color(84, 127, 206));
        jProgressBar1.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 10));
        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);

        jLabel.get(4).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Water_25px.png"))); // NOI18N

        jLabel.get(14).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Secured_Letter_25px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel.get(3));
        jPanel.get(3).setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel.get(14))
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel.get(0))
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel.get(2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel.get(3)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel.get(4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jSeparator1))))
                                .addGap(40, 40, 40))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel.get(3), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel.get(2), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel.get(0), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel.get(14), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 24, Short.MAX_VALUE))
                                        .addComponent(jLabel.get(4), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel.get(2).add(jPanel.get(3), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, -1, 130));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        jPanel.get(2).add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 24, -1, 46));

        jLabel.get(1).setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/imge_1.jpg"))); // NOI18N
        jPanel.get(2).add(jLabel.get(1), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 86, -1));

        jLabel.get(11).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(11).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(11).setText(username);
        jPanel.get(2).add(jLabel.get(11), new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 30));

        jLabel.get(5).setFont(new java.awt.Font("Segoe UI", 0, 52)); // NOI18N
        jLabel.get(5).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(5).setText("04");

        button1.setBackground(new java.awt.Color(71, 120, 197));
        button1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(0, 0, 0));
        button1.setLabel("Book");

        insertBtn.setBackground(new java.awt.Color(71, 120, 197));
        insertBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        insertBtn.setForeground(new java.awt.Color(0, 0, 0));
        insertBtn.setLabel("+");

        deleteBtn.setBackground(new java.awt.Color(71, 120, 197));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn.setLabel("-");

        jLabel.get(12).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(12).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(12).setText("May 2018");

        jLabel.get(15).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(15).setForeground(new java.awt.Color(255, 255, 255));
        jLabel.get(15).setText("Friday 23 Feb ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel.get(1));
        jPanel.get(1).setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel.get(2), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel.get(12)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(112, 112, 112)
                                                                .addComponent(jLabel.get(5)))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(73, 73, 73)
                                                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel.get(15))
                                        .addContainerGap(195, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel.get(2), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel.get(12), javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel.get(5))
                                .addGap(25, 25, 25)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(106, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(236, 236, 236)
                                        .addComponent(jLabel.get(15), javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                        .addGap(285, 285, 285)))
        );

        getContentPane().add(jPanel.get(1), new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        jPanel.get(4).setBackground(new java.awt.Color(255, 255, 255));

//        jPanel.get(5).setBackground(new java.awt.Color(242, 247, 247));
        jPanel.get(5).setBackground(new java.awt.Color(230, 230, 240));

        jLabel.get(13).setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel.get(13).setForeground(new java.awt.Color(102, 102, 102));
        jLabel.get(13).setText("Launch dates for the items listed ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel.get(5));
        jPanel.get(5).setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel.get(13))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel.get(13), javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                .addGap(113, 113, 113))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {"2020-11-11", "Food", "Pizza", "Seoul", 0, 8000, 0},
                        {"2020-11-24", "Beverage", "Coffee", "Seoul", 0, 5000, 0},
                        {"2020-11-30", "Public", "Mobile Phone fee", "Seoul", 0, 2000000, 0},
                        {"2020-11-30", "Financial", "Insurance premium", "Seoul", 0, 300000, 0},
                        {"2020-11-25", "Service", "Mac A/S", "Seoul", 0, 12000, 0},
                        {"2020-11-30", "Medical", "Dental care", "Dongtan", 0, 45000, 0},
                        {"2020-11-30", "Income", "Nov salary", "Seoul", 10000000, 0, 0},
                        {"2020-12-01", "Clothes", "A.P.C shirt", "Daegu", 0, 185000, 0},
                        {"2020-12-07", "Hobby", "Steam game", "Daegu", 0, 36000, 0},
                        {"2020-12-12", "Business", "Meeting expenses", "Busan", 0, 12000, 0},
                        {"2020-12-17", "Study", "Online study", "Daegu", 0, 330000, 0},
                        {"2020-12-24", "Vehicle", "Fuel", "Busan", 0, 60000, 0},
                        {"2020-12-24", "Etc", "Lost wallet", "Busan", 0, 100000, 0}
                },
                new String[]{
                        "Date", "Type", "Item", "Location", "Credit", "Debit", "Balance"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, String.class, String.class, String.class, Integer.class, Integer.class, Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(230, 230, 240));
        jTable1.setRowHeight(22);
        setJTable();
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel.get(4));
        jPanel.get(4).setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel.get(5), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jPanel.get(5), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel.get(4), new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 650, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Home Tab
    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        setColor(btn.get(0));
        ind.get(0).setOpaque(true);
        resetColor(new JPanel[]{btn.get(1), btn.get(2), btn.get(3)}, new JPanel[]{ind.get(1), ind.get(2), ind.get(3)});
    }//GEN-LAST:event_btn_1MousePressed

    private void btn_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseReleased
        // TODO add your handling code here:
        setColor(btn.get(1));
        ind.get(1).setOpaque(true);
        resetColor(new JPanel[]{btn.get(0), btn.get(2), btn.get(3)}, new JPanel[]{ind.get(0), ind.get(2), ind.get(3)});
    }//GEN-LAST:event_btn_2MouseReleased

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:
        setColor(btn.get(2));
        ind.get(2).setOpaque(true);
        resetColor(new JPanel[]{btn.get(1), btn.get(0), btn.get(3)}, new JPanel[]{ind.get(1), ind.get(0), ind.get(3)});
    }//GEN-LAST:event_btn_3MousePressed
    // Profile Tab
    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
        // TODO add your handling code here:
        setColor(btn.get(3));
        ind.get(3).setOpaque(true);
        resetColor(new JPanel[]{btn.get(1), btn.get(2), btn.get(0)}, new JPanel[]{ind.get(1), ind.get(2), ind.get(0)});
    }//GEN-LAST:event_btn_4MousePressed

    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();

    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
//        this.setLocation(x - xx, y - xy);
        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "You have logged out.");
        setVisible(false);
        new LogIn();
//        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(23, 35, 51));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }



    private void setJTable(){
        try{
            PreparedStatement ps = connection.prepareStatement("Select * from ledger");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);

            while(rs.next()){
                Object o[] = {rs.getDate("date"),rs.getString("type"),rs.getString("item"),rs.getString("location"),rs.getInt("credit"),rs.getInt("debit"),rs.getInt("balance")};
                tm.addRow(o);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in Employee Grid View..... "+e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private List<JPanel> btn;
    private List<JPanel> ind;
    private List<JLabel> jLabel;
    private List<JPanel> jPanel;

    private JLabel btn_exit;
    private java.awt.Button button1;
    private JButton insertBtn;
    private JButton deleteBtn;

    private JProgressBar jProgressBar1;
    private JScrollPane jScrollPane1;
    private JSeparator jSeparator1;
    private JTable jTable1;
    private JTextField jTextField1;
    private JPanel side_pane;
    // End of variables declaration//GEN-END:variables
}
